export enum AuthErrors {
  InvalidCredentials = "InvalidCredentials",
  UserNotFound = "UserNotFound",
  AccountLocked = "AccountLocked",
  CONFLICT = "CONFLICT",
  CredentialsSignin = "CredentialsSignin",
  CredentialsCallback = "CredentialsCallback",
  AccountSignin = "AccountSignin",
  AccountCallback = "AccountCallback",
  OAuthSignin = "OAuthSignin",
  OAuthCallback = "OAuthCallback",
  OAuthCreateAccount = "OAuthCreateAccount",
  EmailCreateAccount = "EmailCreateAccount",
  EmailSignin = "EmailSignin",
  VerificationEmailSent = "VerificationEmailSent",
  EmailNotVerified = "EmailNotVerified",
  SessionRequired = "SessionRequired",
}
